runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /highrun_rules.html
  static_files: highrun_rules.html
  upload: highrun_rules.html

- url: /css/
  static_dir: css

- url: /apps/
  static_dir: apps

- url: /js
  static_dir: js

- url: /results/
  static_dir: results

- url: /seasons/
  static_dir: seasons

- url: /stylesheets
  static_dir: stylesheets

- url: /admin/
  script: admin.admin.app
  login: required

- url: /[^/]*/suggest/
  script: admin.suggestMatch.app

- url: /[^/]*/admin/
  script: admin.admin.app
  login: required

- url: /admin/addClub/
  script: admin.addClub.app
  login: admin

- url: /admin/uploadPhoto/
  script: admin.uploadPhoto.app
  login: required

- url: /[^/]*/admin/upload
  script: admin.saveResults.app
  login: required

- url: /[^/]*/admin/(.*)/
  script: admin.\1.app
  login: required

- url: /[^/]*/details/.*
  script: details.app

- url: /[^/]*/hr/
  script: hr.app

- url: /[^/]*/charts/.*
  script: charts.app

- url: /[^/]*/weekly/.*
  script: weekly.app

- url: /[^/]*/players/.*
  script: players.app

- url: /players/.*
  script: players.app

- url: /showResults/.*
  script: showResults.app

- url: /showPhoto/.*
  script: showPhoto.app

- url: /[^/]*/
  script: view.app

- url: /
  script: view.app


builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

