application: aspastats
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /results/
  static_dir: results

- url: /seasons/
  static_dir: seasons

- url: /stylesheets
  static_dir: stylesheets

- url: /admin
  script: admin.app

- url: /admin/
  script: admin.app

- url: /admin/addClub/
  script: addClub.app

- url: /admin/addSeason/
  script: addSeason.app

- url: /admin/addPlayer/
  script: addPerson.app

- url: /admin/addMatch/
  script: addMatch.app

- url: /admin/suggestMatch/
  script: suggestMatch.app

- url: /admin/adjustHandicap/
  script: adjustHandicap.app

- url: /admin/destroy/
  script: destroy.app

- url: /admin/regenerate/
  script: fakeData.app

- url: /details/.*
  script: details.app

- url: /
  script: view.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
